extends:
  - react-app
  - ../.eslintrc.yml
parserOptions:
  project: ./tsconfig.json
overrides:
  - files:
      - vite.config.ts
    parserOptions:
      project: ./tsconfig.node.json
rules:
  '@typescript-eslint/no-restrictes-imports':
    - error
    - patterns:
        - group:
            - '@brainstormer/backend/**'
            - '!@brainstormer/backend/**/'
            - '!@brainstormer/backend/**/input'
          allowTypeImports: true
          message: 'Only types and input schemas are allowed to be imported from backend workspace'
